INSERT INTO recipeList (recipeID, recipeLink)
VALUES
(1, 'appleNacho.html'),
(2, 'baked_potato'),
(3, 'banana_pancake.html'),
(4, 'cauliStirFry.html'),
(5, 'cheese_noodles.html'),
(6, 'chickfry.html'),
(7, 'chickpeaSalad.html'),
(8, 'cinnamonSugarChips.html'),
(9, 'cookieDough.html'),
(10, 'eggScarmbleVeg.html'),
(11, 'greekYogurt.html'),
(12, 'grilled_cheese.html'),
(13, 'honey_butter_toast.html'),
(14, 'iceCreamB.html'),
(15, 'mac_and_cheese.html'),
(16, 'mugBrownie.html'),
(17, 'mugCake.html'),
(18, 'oatmeal.html'),
(19, 'pot_pie.html'),
(20, 'quesadilla_nachos.html'),
(21, 'ramen_upgrade.html'),
(22, 'riceKrispie.html'),
(23, 'smores.html'),
(24, 'soup.html'),
(25, 'tomato_soup.html'),
(26, 'tunaSaladWrap.html'),
(27, 'veggieStirFry.html'),
(29, 'zuchNoodles.html');

